# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('comments', models.TextField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'created', b'Created'), (b'approved', b'Approved')], max_length=10)),
                ('purchase_order_number', models.CharField(max_length=10)),
                ('currency', models.CharField(choices=[(b'pounds', b'Pounds'), (b'dollars', b'Dollars'), (b'euros', b'Euros')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.Supplier'),
        ),
    ]
