# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('all_day', models.CharField(choices=[(b'all_day', b'All Day'), (b'morning', b'Morning'), (b'afternoon', b'Afternoon')], max_length=10)),
            ],
        ),
    ]
