# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190103_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='TimeOffRequest',
        ),
    ]
