# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_timeoffrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='type',
            field=models.CharField(choices=[(b'holiday', b'Holiday'), (b'off_sick', b'Off Sick'), (b'working_from_home', b'Working From Home')], default=b'holiday', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='all_day',
            field=models.CharField(choices=[(b'all_day', b'All Day'), (b'morning', b'Morning'), (b'afternoon', b'Afternoon')], default=b'all_day', max_length=10),
        ),
    ]
