# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181010_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='holiday_status',
            field=models.TextField(choices=[(b'Approved', b'Approved'), (b'PendingApproval', b'Pending Approval'), (b'NotApproved', b'Not Approved')], default=b'PendingApproval', max_length=10),
        ),
    ]
