# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_timeoffrequest_holiday_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='hruser',
            name='job_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='holiday_status',
            field=models.CharField(choices=[(b'approved', b'Approved'), (b'pending_approval', b'Pending Approval'), (b'not_approved', b'Not Approved')], default=b'pending_approval', max_length=30),
        ),
    ]
