# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181011_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hruser',
            old_name='job_title',
            new_name='job_tittle',
        ),
        migrations.AddField(
            model_name='hruser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department'),
        ),
        migrations.AddField(
            model_name='hruser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='type',
            field=models.CharField(choices=[(b'holiday', b'Holiday'), (b'off_sick', b'Off Sick'), (b'working_from_home', b'Working From Home')], default=b'holiday', max_length=20),
        ),
    ]
