# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181014_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hruser',
            old_name='job_tittle',
            new_name='job_title',
        ),
    ]
