# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181015_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='account_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='emergency_contact_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='emergency_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='emergency_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='iban',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='nationality',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='nin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='private_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='status',
            field=models.CharField(blank=True, choices=[(b'active', b'Active'), (b'inactive', b'Inactive')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='swift_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='tax_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hruser',
            name='work_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
    ]
