# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181018_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=b'static/images'),
        ),
    ]
