# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181120_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hruser',
            name='profile_picture',
            field=models.ImageField(default=b'images/default.png', null=True, upload_to=b'images'),
        ),
    ]
