# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181126_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hruser',
            name='start_date',
            field=models.DateField(),
        ),
    ]
