# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[(b'approved', b'Approved'), (b'pending_approval', b'Pending Approval'), (b'not_approved', b'Not Approved')], default=b'pending_approval', max_length=30)),
                ('type', models.CharField(choices=[(b'holiday', b'Holiday'), (b'off_sick', b'Off Sick'), (b'working_from_home', b'Working From Home')], default=b'holiday', max_length=20)),
                ('all_day', models.CharField(choices=[(b'all_day', b'All Day'), (b'morning', b'Morning'), (b'afternoon', b'Afternoon')], default=b'all_day', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
